<?php
/**
 * Created by PhpStorm.
 * User: dev
 * Date: 1/25/2018
 * Time: 2:30 PM
 */

namespace app\controllers;

use dektrium\user\controllers\SecurityController;

class LoginController extends SecurityController {

	public function actionLogin() {
		$this->layout = '@app/views/layouts/login';
		return parent::actionLogin(); // TODO: Change the autogenerated stub
	}
}